# Generated by Django 5.0.1 on 2024-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='телефон (обяз)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_town',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
    ]
