# Generated by Django 4.2.11 on 2024-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_dogs_dog_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='female_dog',
            field=models.CharField(blank=True, choices=[('Сука', 'Сука'), ('Кобель', 'Кобель')], max_length=20, null=True, verbose_name='Пол собаки(обяз.)'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='number_bookwork',
            field=models.IntegerField(blank=True, null=True, verbose_name='№ Рабочей книжки'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='breed_dog',
            field=models.CharField(max_length=20, verbose_name='Порода собаки(обяз.)'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dog_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кличка по родословной'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='home_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Домашняя кличка(обяз.)'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='number_chip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер чипа'),
        ),
    ]
