# Generated by Django 5.0.1 on 2024-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на трассу')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_class_com', models.CharField(blank=True, choices=[('ro_dety', 'РО-Дети'), ('ro_shenki', 'РО-Щенки'), ('ro_debut', 'РО-Дебют'), ('ro_veterany', 'РО-Ветераны'), ('ro_1', 'РО-1'), ('ro_2', 'РО-2'), ('ro_3', 'РО-3'), ('ro_4', 'РО-4 (мастер)')], max_length=20, null=True, verbose_name='Класс участия')),
                ('image_list', models.TextField(max_length=500, verbose_name='Список знаков')),
                ('image_data', models.TextField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Трасса',
                'verbose_name_plural': 'Трассы',
            },
        ),
    ]
