# Generated by Django 5.0.1 on 2024-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_competition', models.CharField(max_length=20, verbose_name='Название соревнования')),
                ('image_competition', models.ImageField(blank=True, null=True, upload_to='banner_competition', verbose_name='Баннер соревнования')),
                ('date_competition', models.DateField(blank=True, null=True, verbose_name='Дата соревнования')),
                ('pre_date_competition', models.CharField(blank=True, max_length=40, null=True, verbose_name='Предполагаемый период соревновний')),
                ('start_date_competition', models.DateField(blank=True, null=True, verbose_name='Дата начала регистрации')),
                ('end_date_competition', models.DateField(blank=True, null=True, verbose_name='Дата окончания регистарции')),
                ('send_message_start_competition', models.BooleanField(default=False, verbose_name='Уведомелние о начале регистрации (кому)')),
                ('invitation_competition', models.BooleanField(default=False, verbose_name='Разослать приглашения')),
                ('rules_competition', models.CharField(choices=[('Mankovoi', 'Правила Маньковой'), ('FCI', 'Правила FCI'), ('Over', 'Другое')], max_length=20, verbose_name='Правила')),
                ('status_not_official', models.BooleanField(default=False, verbose_name='Неофициальные (не в графике ркф)')),
                ('status_RKF', models.BooleanField(default=False, verbose_name='В графике РКФ')),
                ('status_open', models.BooleanField(default=False, verbose_name='Открытое')),
                ('status_Tests', models.BooleanField(default=False, verbose_name='Испытания')),
                ('status_Quality', models.BooleanField(default=False, verbose_name='Квалификационные соревнования')),
                ('status_Certificate', models.BooleanField(default=False, verbose_name='Сертификатные CACROb и CACIROb')),
                ('status_Training', models.BooleanField(default=False, verbose_name='Тренировочное')),
                ('place_competition', models.CharField(max_length=50, verbose_name='Адрес проведения соревнования')),
                ('play_ground_competition', models.CharField(choices=[('Open', 'Открытая'), ('Close', 'Закрытая'), ('Weather', 'По погоде')], max_length=20, verbose_name='Тип площадки')),
                ('place_on_map', models.CharField(max_length=150, verbose_name='Карта-точка на яндекс карте ')),
                ('contact_organization', models.CharField(max_length=20, verbose_name='Контакт организатора')),
                ('club_organization', models.CharField(blank=True, max_length=20, null=True, verbose_name='Клуб-организатор')),
                ('logo_club_organization', models.ImageField(blank=True, null=True, upload_to='logo_clubs', verbose_name='Логотип клуба организатора')),
                ('judge_competition', models.CharField(max_length=20, verbose_name='Основной судья соревнований')),
                ('class_ro_dety', models.BooleanField(default=False, verbose_name='РО-дети')),
                ('class_ro_shenki', models.BooleanField(default=False, verbose_name='РО-щенки')),
                ('class_ro_debut', models.BooleanField(default=False, verbose_name='РО-дебют')),
                ('class_ro_veterany', models.BooleanField(default=False, verbose_name='РО-ветераны')),
                ('class_ro_1', models.BooleanField(default=False, verbose_name='РО-1')),
                ('class_ro_2', models.BooleanField(default=False, verbose_name='РО-2')),
                ('class_ro_3', models.BooleanField(default=False, verbose_name='РО-3')),
                ('class_ro_4', models.BooleanField(default=False, verbose_name='РО-4(мастера)')),
                ('judge_class_ro_dety', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-дети')),
                ('judge_class_ro_shenki', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-щенки')),
                ('judge_class_ro_debut', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-дебют')),
                ('judge_class_ro_veterany', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-ветераны')),
                ('judge_class_ro_1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-1')),
                ('judge_class_ro_2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-2')),
                ('judge_class_ro_3', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-3')),
                ('judge_class_ro_4', models.CharField(blank=True, max_length=25, null=True, verbose_name='Судья РО-4(мастера)')),
                ('max_players', models.IntegerField(default=1, verbose_name='максимиум участников')),
                ('more_players', models.BooleanField(default=False, verbose_name='участники сверх максимума')),
                ('comment_for_competition', models.TextField(max_length=500, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
    ]
