# Generated by Django 5.0.1 on 2024-03-11 06:26

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image_competition',
            field=models.ImageField(blank=True, null=True, upload_to='banner_competition', validators=[main.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Баннер соревнования (<1мб, 600х600 px)'),
        ),
    ]
