# Generated by Django 4.2.11 on 2024-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_competition_image_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-2'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-3'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-4(мастера)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_debut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-дебют'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_dety',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-дети'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_shenki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-щенки'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_class_ro_veterany',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников РО-ветераны'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-2'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-3'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-4(мастера)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_debut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-дебют'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_dety',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-дети'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_shenki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-щенки'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_reserve_class_ro_veterany',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников в резерве РО-ветераны'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-2'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-3'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-4(мастера)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_debut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-дебют'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_dety',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-дети'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_shenki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-щенки'),
        ),
        migrations.AddField(
            model_name='competition',
            name='count_vnezachet_class_ro_veterany',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум участников внезачет РО-ветераны'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_1',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_2',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-2'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_3',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-3'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_4',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-4(мастера)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_debut',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-дебют'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_dety',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-дети'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_shenki',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-щенки'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reserve_class_ro_veterany',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Возможность резерва РО-ветераны'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_1',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-1'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_2',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-2'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_3',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-3'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_4',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-4(мастера)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_debut',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-дебют'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_dety',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-дети'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_shenki',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-щенки'),
        ),
        migrations.AddField(
            model_name='competition',
            name='vnezachet_class_ro_veterany',
            field=models.BooleanField(default=False, verbose_name='Возможность участия внезачет РО-ветераны'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_players',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='максимиум участников'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='more_players',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='участники сверх максимума'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='place_competition',
            field=models.CharField(max_length=50, verbose_name='Город соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rules_competition',
            field=models.CharField(choices=[('Mankovoi', 'Спб Маньковой 2024'), ('FCI', 'Правила FCI'), ('Over', 'Маньково старое')], max_length=20, verbose_name='Правила'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='send_message_start_competition',
            field=models.BooleanField(default=False, verbose_name='Уведомелние о начале регистрации (организатору)'),
        ),
    ]
