# Generated by Django 5.0.1 on 2024-03-11 05:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_dog', models.CharField(blank=True, choices=[('ro_dety', 'РО-Дети'), ('ro_shenki', 'РО-Щенки'), ('ro_debut', 'РО-Дебют'), ('ro_veterany', 'РО-Ветераны'), ('ro_1', 'РО-1'), ('ro_2', 'РО-2'), ('ro_3', 'РО-3'), ('ro_4', 'РО-4 (мастер)')], max_length=20, null=True, verbose_name='Класс собаки')),
                ('competition', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название соревнования')),
                ('date_competition', models.DateField(blank=True, null=True, verbose_name='Дата соревнования')),
                ('track1_points', models.IntegerField(blank=True, null=True, verbose_name='Количество очков, трасса 1')),
                ('track1_grade', models.CharField(blank=True, choices=[('excellent', 'Отлично'), ('very_good', 'Очень хорошо'), ('good', 'Хорошо'), ('not_enough', 'Недостаточно')], max_length=20, null=True, verbose_name='Оценка собаки, трасса 1')),
                ('track1_time', models.DurationField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600))], verbose_name='Время на трассе 1')),
                ('track1_place', models.IntegerField(blank=True, null=True, verbose_name='Место, трасса 1')),
                ('track2_points', models.IntegerField(blank=True, null=True, verbose_name='Количество очков, трасса 2')),
                ('track2_grade', models.CharField(blank=True, choices=[('excellent', 'Отлично'), ('very_good', 'Очень хорошо'), ('good', 'Хорошо'), ('not_enough', 'Недостаточно')], max_length=20, null=True, verbose_name='Оценка собаки, трасса 2')),
                ('track2_time', models.DurationField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600))], verbose_name='Время на трассе 2')),
                ('track2_place', models.IntegerField(blank=True, null=True, verbose_name='Место, трасса 2')),
            ],
            options={
                'verbose_name': 'История соревнования',
                'verbose_name_plural': 'История соревнований',
            },
        ),
    ]
