# Generated by Django 5.0.1 on 2024-03-11 05:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_scores', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conductor', models.CharField(max_length=10, unique=True, verbose_name='ID Проводника')),
                ('check_admin', models.BooleanField(default=False, verbose_name='Одобрен админом')),
            ],
            options={
                'verbose_name': 'Проводник',
                'verbose_name_plural': 'Проводники',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_judge', models.CharField(max_length=20, verbose_name='ID судьи')),
                ('judge_status', models.BooleanField(default=False, verbose_name='Статус судьи запрошен')),
                ('check_admin', models.BooleanField(default=False, verbose_name='Одобрен админом')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_competitor', models.CharField(blank=True, choices=[('great', 'Отлично'), ('very_good', 'Очень хорошо'), ('good', 'Хорошо'), ('not_enough', 'Недостаточно')], max_length=20, null=True, verbose_name='Оценка участника')),
                ('points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Количество очков')),
                ('class_comp', models.CharField(blank=True, choices=[('ro_dety', 'РО-Дети'), ('ro_shenki', 'РО-Щенки'), ('ro_debut', 'РО-Дебют'), ('ro_veterany', 'РО-Ветераны'), ('ro_1', 'РО-1'), ('ro_2', 'РО-2'), ('ro_3', 'РО-3'), ('ro_4', 'РО-4 (мастер)')], max_length=20, null=True, verbose_name='Класс участия')),
                ('min_time_competitor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)], verbose_name='Мин')),
                ('sec_time_competitor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)], verbose_name='Сек')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
